import React,{useEffect,useMemo,useState} from 'react'
import {WalletCards,Filter,Plus,Search,MoreHorizontal,Pencil,Trash2,ReceiptText} from 'lucide-react'
import {addExpense,deleteExpense,getExpenses,updateExpense} from '../lib/businessStore'
import BusinessModal from '../components/BusinessModal'
import {useI18n} from '../i18n/I18n'
import '../styles/business-desktop.css'
const EMPTY={category:'Shipping',description:'',amount:'',date:new Date().toISOString().slice(0,10),project:'',method:'Cash',invoice:'',notes:''}
const COLORS={Materials:'#FB7DA8',Shipping:'#058CD7',Advertising:'#552CB7',Packaging:'#FFC567',Equipment:'#FD5A46',Energy:'#F59E0B',Other:'#94A3B8'}
export default function Expenses(){const {lang}=useI18n(),L=labels(lang);const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[month,setMonth]=useState(()=>new Date().toISOString().slice(0,7)),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(EMPTY),[menu,setMenu]=useState(null)
 async function load(){setLoading(true);try{setRows(await getExpenses())}finally{setLoading(false)}} useEffect(()=>{load()},[])
 const filtered=useMemo(()=>rows.filter(r=>(!month||String(r.date||'').startsWith(month))&&(!query.trim()||[r.category,r.description,r.project,r.method].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase())))),[rows,query,month]);const total=filtered.reduce((s,r)=>s+(Number(r.amount)||0),0);const byCat=useMemo(()=>Object.entries(filtered.reduce((a,r)=>{a[r.category]=(a[r.category]||0)+(Number(r.amount)||0);return a},{})).sort((a,b)=>b[1]-a[1]),[filtered]);const avg=filtered.length?total/filtered.length:0
 function startAdd(){setEditing(null);setForm({...EMPTY,date:new Date().toISOString().slice(0,10)});setOpen(true)} function startEdit(r){setEditing(r.id);setForm({...EMPTY,...r});setMenu(null);setOpen(true)} async function save(e){e.preventDefault();if(!form.amount)return;editing?await updateExpense(editing,form):await addExpense(form);setOpen(false);setEditing(null);await load()} async function remove(id){if(!confirm(L.confirmDelete))return;await deleteExpense(id);setMenu(null);await load()}
 return <div className="biz-page expenses-page"><section className="biz-frame expenses-frame"><span className="biz-number expenses-number">3</span><header className="biz-page-head"><div className="biz-title-wrap"><span className="biz-title-icon expenses-icon"><WalletCards/></span><div><h1>{L.expenses}</h1><p>{L.sub}</p></div></div><div className="biz-head-actions"><div className="biz-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={L.search}/></div><button className="biz-soft-btn"><Filter/>{L.filter}</button><button className="biz-primary expenses-primary" onClick={startAdd}><Plus/>{L.add}</button></div></header>
  <div className="expenses-layout"><div className="biz-table-wrap"><table className="biz-table expenses-table"><thead><tr><th>{L.category}</th><th>{L.description}</th><th>{L.amount}</th><th>{L.date}</th><th>{L.project}</th><th>{L.method}</th><th>{L.invoice}</th><th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><div className="expense-cat"><i style={{background:COLORS[r.category]||COLORS.Other}}/><strong>{catLabel(r.category,L)}</strong></div></td><td>{r.description||'—'}</td><td><strong>{eur(r.amount)}</strong></td><td>{formatDate(r.date,lang)}</td><td>{r.project||'—'}</td><td><span className="method-pill">{r.method}</span></td><td>{r.invoice?<ReceiptText title={r.invoice}/>:<span>—</span>}</td><td className="menu-cell"><button className="dots" onClick={()=>setMenu(menu===r.id?null:r.id)}><MoreHorizontal/></button>{menu===r.id&&<div className="row-menu"><button onClick={()=>startEdit(r)}><Pencil/>{L.edit}</button><button className="danger" onClick={()=>remove(r.id)}><Trash2/>{L.delete}</button></div>}</td></tr>)}</tbody></table>{loading&&<div className="biz-empty">{L.loading}</div>}{!loading&&!filtered.length&&<div className="biz-empty">{L.empty}</div>}</div>
  <aside className="expenses-summary"><input className="month-input" type="month" value={month} onChange={e=>setMonth(e.target.value)}/><h3>{L.totalExpenses}</h3><strong className="expenses-total">{eur(total)}</strong><ExpenseDonut rows={byCat} total={total}/><div className="expense-legend">{byCat.map(([k,v])=><div key={k}><span><i style={{background:COLORS[k]||COLORS.Other}}/>{catLabel(k,L)}</span><b>{eur(v)} <small>({total?Math.round(v/total*100):0}%)</small></b></div>)}</div><div className="expense-kpis"><div><small>{L.monthAverage}</small><strong>{eur(avg)}</strong></div><div><small>{L.transactions}</small><strong>{filtered.length}</strong></div></div></aside></div>
 </section>
 <BusinessModal open={open} onClose={()=>setOpen(false)} title={editing?L.editExpense:L.add} subtitle={L.formSub} wide><form className="biz-form two-col" onSubmit={save}><label><span>{L.category}</span><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{Object.keys(COLORS).map(k=><option key={k} value={k}>{catLabel(k,L)}</option>)}</select></label><label><span>{L.amount}</span><div className="input-unit"><b>€</b><input inputMode="decimal" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} required/></div></label><label><span>{L.date}</span><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label><span>{L.project}</span><input value={form.project} onChange={e=>setForm({...form,project:e.target.value})}/></label><label><span>{L.method}</span><select value={form.method} onChange={e=>setForm({...form,method:e.target.value})}><option>Cash</option><option>Card</option><option>Bank</option></select></label><label><span>{L.invoice}</span><input value={form.invoice} onChange={e=>setForm({...form,invoice:e.target.value})}/></label><label className="span-2"><span>{L.description}</span><input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="span-2"><span>{L.notes}</span><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="biz-form-actions span-2"><button type="button" className="biz-soft-btn" onClick={()=>setOpen(false)}>{L.cancel}</button><button className="biz-primary expenses-primary">{L.save}</button></div></form></BusinessModal></div>}
function ExpenseDonut({rows,total}){let pos=0;const seg=rows.map(([k,v])=>{const p=total?v/total*100:0,a=pos;pos+=p;return `${COLORS[k]||COLORS.Other} ${a}% ${pos}%`});return <div className="donut expense-donut" style={{background:seg.length?`conic-gradient(${seg.join(',')})`:'#eee'}}><div/></div>}
function eur(v){return new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(v)||0)} function formatDate(v,lang){if(!v)return'—';return new Intl.DateTimeFormat(lang==='sq'?'sq-AL':lang==='de'?'de-DE':'en-GB').format(new Date(`${v}T12:00:00`))} function catLabel(k,L){return ({Materials:L.materials,Shipping:L.shipping,Advertising:L.advertising,Packaging:L.packaging,Equipment:L.equipment,Energy:L.energy,Other:L.other})[k]||k}
function labels(lang){const sq={expenses:'Shpenzimet',sub:'Monitoro shpenzimet e studios dhe kontrollo buxhetin.',search:'Kërko shpenzim...',filter:'Filtro',add:'Shto shpenzim',category:'Kategoria',description:'Përshkrimi',amount:'Shuma',date:'Data',project:'Projekti',method:'Metoda',invoice:'Faturë',totalExpenses:'Totali i shpenzimeve',monthAverage:'Mesatarja',transactions:'Transaksione',materials:'Materiale',shipping:'Postë / Transport',advertising:'Reklama',packaging:'Paketim',equipment:'Pajisje',energy:'Energjia',other:'Të tjera',edit:'Redakto',delete:'Fshi',loading:'Duke ngarkuar...',empty:'Nuk ka shpenzime për këtë periudhë.',editExpense:'Redakto shpenzimin',formSub:'Shpenzimi ruhet në Firestore dhe mund të lidhet me projekt.',notes:'Shënime',cancel:'Anulo',save:'Ruaj shpenzimin',confirmDelete:'Ta fshij këtë shpenzim?'};const de={...sq,expenses:'Ausgaben',sub:'Studioausgaben überwachen und Budget kontrollieren.',search:'Ausgaben suchen...',filter:'Filter',add:'Ausgabe hinzufügen',category:'Kategorie',description:'Beschreibung',amount:'Betrag',date:'Datum',project:'Projekt',method:'Methode',invoice:'Beleg',totalExpenses:'Gesamtausgaben',monthAverage:'Durchschnitt',transactions:'Transaktionen',materials:'Materialien',shipping:'Post / Transport',advertising:'Werbung',packaging:'Verpackung',equipment:'Ausrüstung',energy:'Energie',other:'Sonstiges',edit:'Bearbeiten',delete:'Löschen',loading:'Wird geladen...',empty:'Keine Ausgaben in diesem Zeitraum.',editExpense:'Ausgabe bearbeiten',formSub:'Die Ausgabe wird in Firestore gespeichert.',notes:'Notizen',cancel:'Abbrechen',save:'Ausgabe speichern',confirmDelete:'Diese Ausgabe löschen?'};const en={...sq,expenses:'Expenses',sub:'Monitor studio expenses and control your budget.',search:'Search expense...',filter:'Filter',add:'Add expense',category:'Category',description:'Description',amount:'Amount',date:'Date',project:'Project',method:'Method',invoice:'Receipt',totalExpenses:'Total expenses',monthAverage:'Average',transactions:'Transactions',materials:'Materials',shipping:'Post / Transport',advertising:'Advertising',packaging:'Packaging',equipment:'Equipment',energy:'Energy',other:'Other',edit:'Edit',delete:'Delete',loading:'Loading...',empty:'No expenses in this period.',editExpense:'Edit expense',formSub:'The expense is saved in Firestore.',notes:'Notes',cancel:'Cancel',save:'Save expense',confirmDelete:'Delete this expense?'};return lang==='de'?de:lang==='en'?en:sq}
