import React,{useEffect,useMemo,useRef,useState} from 'react'
import {Banknote,Filter,Package,Plus,Search,Truck,WalletCards,Wrench,Zap,Megaphone,Boxes,X,Save,Trash2,CalendarDays,FileText} from 'lucide-react'
import {useI18n} from '../i18n/I18n'
import {getProjects} from '../lib/projectsStore'
import {createExpense,deleteExpense,getExpenses,updateExpense,getBusinessReports,createBusinessReport,deleteBusinessReport} from '../lib/businessStore'
import {makeBusinessPdf} from '../lib/businessPdf'
import '../styles/business-pc.css'
const CAT_ICON={'Post & Transport':Truck,'Packaging':Package,'Energy':Zap,'Materials':Boxes,'Equipment':Wrench,'Advertising':Megaphone,'Other':Banknote}
const CAT_COLOR={'Post & Transport':'#058CD7','Packaging':'#552CB7','Energy':'#FFC567','Materials':'#00995E','Equipment':'#058CD7','Advertising':'#FD5A46','Other':'#FB7DA8'}
export default function Expenses(){
 const {lang}=useI18n(),tx=labels(lang),dialog=useRef(null)
 const [rows,setRows]=useState([]),[reports,setReports]=useState([]),[projects,setProjects]=useState([]),[q,setQ]=useState(''),[editing,setEditing]=useState(null),[saving,setSaving]=useState(false),[month,setMonth]=useState(currentMonth()),[mobileCat,setMobileCat]=useState('all'),[mobileDetail,setMobileDetail]=useState(null)
 async function load(){const[a,b,c]=await Promise.all([getExpenses().catch(()=>[]),getProjects().catch(()=>[]),getBusinessReports('expenses').catch(()=>[])]);setRows(a);setProjects(b);setReports(c)}
 useEffect(()=>{load()},[])
 const shown=useMemo(()=>rows.filter(r=>String(r.date||'').startsWith(month)&&[r.category,r.description,r.project_name,r.payment_method].join(' ').toLowerCase().includes(q.toLowerCase())),[rows,q,month])
 const total=shown.reduce((s,r)=>s+num(r.amount),0),byCat=useMemo(()=>{const m={};shown.forEach(r=>m[r.category]=(m[r.category]||0)+num(r.amount));return Object.entries(m).sort((a,b)=>b[1]-a[1])},[shown])
 function open(row=null){setEditing(row);dialog.current?.showModal()}function close(){dialog.current?.close();setEditing(null)}
 async function submit(e){e.preventDefault();setSaving(true);const f=new FormData(e.currentTarget),p=projects.find(x=>x.id===f.get('project_id'));const data={category:String(f.get('category')||'Other'),description:String(f.get('description')||'').trim(),amount:num(f.get('amount')),date:String(f.get('date')||new Date().toISOString().slice(0,10)),project_id:String(f.get('project_id')||''),project_name:String(p?.name||editing?.project_name||''),payment_method:String(f.get('payment_method')||'Cash'),invoice_ref:String(f.get('invoice_ref')||'').trim(),notes:String(f.get('notes')||'')};if(editing)await updateExpense(editing.id,data);else await createExpense(data);await load();setSaving(false);close()}
 async function remove(id){if(!confirm(tx.confirmDelete))return;await deleteExpense(id);await load();close()}
 async function pdf(){const lines=[`#${monthLabel(month,lang)}`,`${tx.monthTotal}: €${money(total)}`,`${tx.transactions}: ${shown.length}`,'',...shown.flatMap(r=>[`${categoryLabel(r.category,tx)} – €${money(r.amount)}`,`${tx.description}: ${r.description||'—'}   |   ${tx.date}: ${formatDate(r.date)}   |   ${tx.project}: ${r.project_name||'—'}   |   ${tx.method}: ${r.payment_method||'—'}`,''])];const file=makeBusinessPdf({title:tx.pdfTitle,subtitle:tx.subtitle,lines,filename:`expenses-${month}.pdf`});await createBusinessReport({module:'expenses',title:`${tx.pdfTitle} – ${monthLabel(month,lang)}`,file_name:file,lines});await load()}
 async function openReport(r){makeBusinessPdf({title:r.title||tx.pdfTitle,subtitle:tx.subtitle,lines:r.lines||[],filename:r.file_name||'expenses.pdf'})}
 return <div className="business-page expenses retro-business-page">
 <MobileExpenses tx={tx} rows={rows} shown={shown} q={q} setQ={setQ} month={month} setMonth={setMonth} cat={mobileCat} setCat={setMobileCat} open={open} detail={mobileDetail} setDetail={setMobileDetail} total={total} byCat={byCat}/>
 <section className="business-shell-card biz-desktop-only"><header className="business-head"><div className="business-number">3</div><div className="business-title-icon"><WalletCards/></div><div className="business-heading"><h1>{tx.title}</h1><p>{tx.subtitle}</p></div><div className="business-actions"><button className="biz-btn retro-purple" onClick={pdf}>PDF</button><label className="biz-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={tx.search}/></label><button className="biz-btn"><Filter/>{tx.filter}</button><button className="biz-btn primary" onClick={()=>open()}><Plus/>{tx.add}</button></div></header>
  <div className="biz-layout-split"><div className="business-table-wrap"><table className="business-table expenses-table"><thead><tr><th>{tx.category}</th><th>{tx.description}</th><th>{tx.amount}</th><th>{tx.date}</th><th>{tx.project}</th><th>{tx.method}</th><th>{tx.invoice}</th><th/></tr></thead><tbody>{shown.map(r=>{const I=CAT_ICON[r.category]||Banknote;return <tr key={r.id}><td><div className="biz-person"><span className="biz-expense-icon" style={{color:CAT_COLOR[r.category]||'#777'}}><I/></span><b>{categoryLabel(r.category,tx)}</b></div></td><td>{r.description||'—'}</td><td className="biz-money">€{money(r.amount)}</td><td>{formatDate(r.date)}</td><td>{r.project_name||'—'}</td><td><span className="payment-pill">{r.payment_method||'—'}</span></td><td>{r.invoice_ref||'—'}</td><td><button className="biz-kebab" onClick={()=>open(r)}>•••</button></td></tr>})}</tbody></table>{!shown.length&&<div className="biz-empty">{tx.empty}</div>}</div>
   <aside className="biz-summary colorful-summary"><select className="biz-month-select" value={month} onChange={e=>setMonth(e.target.value)}>{monthOptions().map(x=><option key={x} value={x}>{monthLabel(x,lang)}</option>)}</select><div className="biz-month-card"><label>{tx.monthTotal}</label><strong>€{money(total)}</strong></div><div className="biz-donut" style={{background:expenseGradient(byCat)}}><div className="biz-donut-center"><b>{tx.total}</b><strong>€{money(total)}</strong></div></div><div className="biz-legend">{byCat.map(([cat,val])=><div className="biz-legend-row" key={cat}><i className="biz-legend-dot" style={{background:CAT_COLOR[cat]||'#aaa'}}/><span>{categoryLabel(cat,tx)}</span><b>€{money(val)}</b></div>)}</div><div className="biz-bottom-stats"><div className="biz-mini-stat pink"><span>{tx.average}</span><strong>€{money(shown.length?total/shown.length:0)}</strong></div><div className="biz-mini-stat good"><span>{tx.transactions}</span><strong>{shown.length}</strong></div></div></aside>
  </div></section><SavedReports title={tx.saved} reports={reports} openReport={openReport} onDelete={async id=>{await deleteBusinessReport(id);await load()}}/>
  <dialog className="biz-dialog retro-dialog expenses-dialog" ref={dialog} onClose={()=>setEditing(null)}><div className="biz-dialog-head retro-dialog-head"><div className="business-title-icon"><WalletCards/></div><div><h2>{editing?tx.edit:tx.add}</h2><p>{tx.dialogSubtitle}</p></div><button className="biz-dialog-close" onClick={close}><X/></button></div><form className="biz-form retro-form" onSubmit={submit} key={editing?.id||'new'}>
   <section className="retro-field-card coral"><div className="retro-field-title"><WalletCards/>{tx.category}</div><select name="category" defaultValue={editing?.category||'Post & Transport'}>{Object.keys(CAT_ICON).map(x=><option key={x}>{x}</option>)}</select></section>
   <section className="retro-field-card yellow"><div className="retro-field-title">€ {tx.amount}</div><input name="amount" type="number" min="0" step="0.01" required defaultValue={editing?.amount||''}/></section>
   <section className="retro-field-card purple full"><div className="retro-field-title"><FileText/>{tx.description}</div><input name="description" required defaultValue={editing?.description||''}/></section>
   <section className="retro-field-card blue"><div className="retro-field-title"><CalendarDays/>{tx.date}</div><input name="date" type="date" defaultValue={editing?.date||new Date().toISOString().slice(0,10)}/></section>
   <section className="retro-field-card green"><div className="retro-field-title">{tx.project}</div><select name="project_id" defaultValue={editing?.project_id||''}><option value="">—</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></section>
   <section className="retro-field-card pink"><div className="retro-field-title">{tx.method}</div><select name="payment_method" defaultValue={editing?.payment_method||'Cash'}><option>Cash</option><option>Card</option><option>Bank</option><option>PayPal</option><option>Other</option></select></section>
   <section className="retro-field-card orange"><div className="retro-field-title">{tx.invoice}</div><input name="invoice_ref" defaultValue={editing?.invoice_ref||''}/></section>
   <section className="retro-field-card full green"><div className="retro-field-title">{tx.notes}</div><textarea name="notes" defaultValue={editing?.notes||''}/></section>
   <div className="biz-form-actions retro-actions">{editing&&<button type="button" className="biz-btn danger" onClick={()=>remove(editing.id)}><Trash2/>{tx.delete}</button>}<button type="button" className="biz-btn" onClick={close}>{tx.cancel}</button><button className="biz-btn retro-save"><Save/>{saving?tx.saving:tx.save}</button></div>
  </form></dialog></div>
}
function MobileExpenses({tx,shown,q,setQ,month,setMonth,cat,setCat,open,detail,setDetail,total,byCat}){
 const list=shown.filter(r=>cat==='all'||r.category===cat)
 const average=list.length?list.reduce((s,r)=>s+num(r.amount),0)/list.length:0
 return <section className="biz-mobile-app biz-mobile-expenses">
  <div className="bma-head"><div><h1>{tx.title}</h1><p>{tx.subtitle}</p></div><button className="bma-head-btn purple" onClick={()=>open()}><Plus/></button></div>
  <div className="bma-expense-summary"><div className="bma-month-row"><select value={month} onChange={e=>setMonth(e.target.value)}>{monthOptions().map(x=><option key={x} value={x}>{monthLabel(x,'sq')}</option>)}</select></div><div className="bma-expense-grid"><div><small>{tx.monthTotal}</small><strong>€{money(total)}</strong></div><div className="bma-mini-donut" style={{background:expenseGradient(byCat)}}><span/></div><div className="bma-expense-mini"><span><small>{tx.average}</small><b>€{money(average)}</b></span><span><small>{tx.transactions}</small><b>{list.length}</b></span></div></div></div>
  <label className="bma-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={tx.search}/><Filter/></label>
  <div className="bma-chips">{[['all','Të gjitha'],['Post & Transport',categoryLabel('Post & Transport',tx)],['Packaging',categoryLabel('Packaging',tx)],['Energy',categoryLabel('Energy',tx)],['Other',categoryLabel('Other',tx)]].map(([k,l])=><button key={k} className={cat===k?'active':''} onClick={()=>setCat(k)}>{l}</button>)}</div>
  <div className="bma-list expense">{list.length?list.map(r=>{const I=CAT_ICON[r.category]||Banknote;return <button className="bma-row expense" key={r.id} onClick={()=>setDetail(r)}><span className="bma-exp-icon" style={{color:CAT_COLOR[r.category]||'#6c39d7',background:`${CAT_COLOR[r.category]||'#6c39d7'}18`}}><I/></span><div className="bma-row-main"><div className="bma-row-title"><b>{categoryLabel(r.category,tx)}</b><strong>€{money(r.amount)}</strong></div><small>{formatDate(r.date)}{r.project_name?` · ${r.project_name}`:''}</small><span>{r.description||'—'}</span></div><div className="bma-row-side"><b>›</b></div></button>}):<div className="bma-empty"><WalletCards/><b>{tx.empty}</b><span>{tx.add}</span></div>}</div>
  <button className="bma-primary expense" onClick={()=>open()}><Plus/>{tx.add}</button>
  {detail&&<div className="bma-detail"><div className="bma-detail-head"><button onClick={()=>setDetail(null)}>‹</button><h2>{categoryLabel(detail.category,tx)}</h2></div><div className="bma-detail-card expense"><dl><dt>{tx.amount}</dt><dd>€{money(detail.amount)}</dd><dt>{tx.date}</dt><dd>{formatDate(detail.date)}</dd><dt>{tx.project}</dt><dd>{detail.project_name||'—'}</dd><dt>{tx.method}</dt><dd>{detail.payment_method||'—'}</dd><dt>{tx.invoice}</dt><dd>{detail.invoice_ref||'—'}</dd><dt>{tx.description}</dt><dd>{detail.description||'—'}</dd></dl></div>{detail.notes&&<div className="bma-notes"><b>{tx.notes}</b><p>{detail.notes}</p></div>}<div className="bma-detail-actions"><button onClick={()=>setDetail(null)}>Mbyll</button><button className="dark purple" onClick={()=>{setDetail(null);open(detail)}}>{tx.edit}</button></div></div>}
 </section>
}

function SavedReports({title,reports,openReport,onDelete}){return <section className="saved-docs"><h3>{title}</h3>{reports.length?<div className="saved-doc-grid">{reports.slice(0,8).map(r=><div className="saved-doc" key={r.id}><div><b>{r.title}</b><small>{new Date(r.created_at||Date.now()).toLocaleString()}</small></div><button onClick={()=>openReport(r)}>PDF</button><button className="danger-mini" onClick={()=>onDelete(r.id)}>×</button></div>)}</div>:<p>—</p>}</section>}
function num(v){return Number(v)||0}function money(v){return num(v).toFixed(2)}function formatDate(v){if(!v)return'—';const[y,m,d]=String(v).split('-');return y&&m&&d?`${d}.${m}.${y}`:v}function currentMonth(){return new Date().toISOString().slice(0,7)}function monthOptions(){const a=[],d=new Date();for(let i=0;i<12;i++){const x=new Date(d.getFullYear(),d.getMonth()-i,1);a.push(`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`)}return a}function monthLabel(v,lang){const[y,m]=v.split('-').map(Number);return new Intl.DateTimeFormat(lang==='sq'?'sq-AL':lang==='de'?'de-DE':'en-US',{month:'long',year:'numeric'}).format(new Date(y,m-1,1))}function categoryLabel(v,t){return t.cat?.[v]||v}function expenseGradient(byCat){if(!byCat.length)return'conic-gradient(#eee 0 100%)';const total=byCat.reduce((s,x)=>s+x[1],0)||1;let at=0;const parts=[];for(const[cat,val]of byCat){const next=at+val/total*100;parts.push(`${CAT_COLOR[cat]||'#aaa'} ${at}% ${next}%`);at=next}return`conic-gradient(${parts.join(',')})`}
function labels(lang){const catSq={'Post & Transport':'Postë / Transport','Packaging':'Paketim','Energy':'Energji','Materials':'Materiale','Equipment':'Pajisje','Advertising':'Reklama','Other':'Të tjera'};if(lang==='de')return{title:'Ausgaben',subtitle:'Ausgaben erfassen und Budget kontrollieren.',search:'Ausgaben suchen...',filter:'Filter',add:'Ausgabe hinzufügen',category:'Kategorie',description:'Beschreibung',amount:'Betrag',date:'Datum',project:'Projekt',method:'Zahlung',invoice:'Beleg / Rechnung',notes:'Notizen',monthTotal:'Gesamtausgaben',total:'Gesamt',average:'Durchschnitt',transactions:'Transaktionen',save:'Ausgabe speichern',saving:'Speichern…',cancel:'Schließen',edit:'Ausgabe bearbeiten',delete:'Löschen',empty:'Keine Ausgaben in diesem Monat.',confirmDelete:'Diese Ausgabe löschen?',cat:{'Post & Transport':'Post / Transport','Packaging':'Verpackung','Energy':'Energie','Materials':'Materialien','Equipment':'Ausrüstung','Advertising':'Werbung','Other':'Sonstige'},saved:'Gespeicherte PDFs',pdfTitle:'Tufting Studio – Ausgaben',dialogSubtitle:'Ausgabe, Projekt und Beleg sauber erfassen.'};if(lang==='en')return{title:'Expenses',subtitle:'Record studio expenses and control your budget.',search:'Search expenses...',filter:'Filter',add:'Add expense',category:'Category',description:'Description',amount:'Amount',date:'Date',project:'Project',method:'Payment',invoice:'Receipt / Invoice',notes:'Notes',monthTotal:'Total expenses',total:'Total',average:'Average',transactions:'Transactions',save:'Save expense',saving:'Saving…',cancel:'Close',edit:'Edit expense',delete:'Delete',empty:'No expenses this month.',confirmDelete:'Delete this expense?',cat:{},saved:'Saved PDFs',pdfTitle:'Tufting Studio – Expenses',dialogSubtitle:'Record expense, project and receipt clearly.'};return{title:'Shpenzimet',subtitle:'Regjistro shpenzimet e studios dhe kontrollo buxhetin.',search:'Kërko shpenzim...',filter:'Filtro',add:'Shto shpenzim',category:'Kategoria',description:'Përshkrimi',amount:'Shuma',date:'Data',project:'Projekti',method:'Pagesa',invoice:'Faturë / Kupon',notes:'Shënime',monthTotal:'Totali i shpenzimeve',total:'Totali',average:'Mesatarja',transactions:'Transaksione',save:'Ruaj shpenzimin',saving:'Po ruhet…',cancel:'Mbyll',edit:'Redakto shpenzimin',delete:'Fshi',empty:'Ende nuk ka shpenzime këtë muaj.',confirmDelete:'Ta fshij këtë shpenzim?',cat:catSq,saved:'PDF / Faturat e ruajtura',pdfTitle:'Tufting Studio – Shpenzimet',dialogSubtitle:'Regjistro shpenzimin, projektin dhe faturën qartë.'}}
