import React,{useEffect,useMemo,useState} from 'react'
import {Archive,Download,Plus,Search,MoreHorizontal,Pencil,Trash2,AlertTriangle} from 'lucide-react'
import {addInventoryItem,deleteInventoryItem,getInventory,updateInventoryItem} from '../lib/businessStore'
import BusinessModal from '../components/BusinessModal'
import {useI18n} from '../i18n/I18n'
import '../styles/business-desktop.css'

const EMPTY={type:'Yarn',name:'',color_name:'',color_code:'#FFC567',brand:'',stock_g:'',min_stock_g:'300',price_per_ball:'',ball_g:'100'}
export default function Inventory(){
 const {lang}=useI18n(),L=labels(lang)
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(EMPTY),[menu,setMenu]=useState(null)
 async function load(){setLoading(true);try{setRows(await getInventory())}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const filtered=useMemo(()=>rows.filter(r=>!query.trim()||[r.name,r.color_name,r.color_code,r.brand,r.type].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase()))),[rows,query])
 const totalG=rows.reduce((s,r)=>s+(Number(r.stock_g)||0),0), totalValue=rows.reduce((s,r)=>s+(Number(r.value)||0),0)
 function startAdd(){setEditing(null);setForm(EMPTY);setOpen(true)}
 function startEdit(r){setEditing(r.id);setForm({...EMPTY,...r});setMenu(null);setOpen(true)}
 async function save(e){e.preventDefault();if(!form.name.trim())return;editing?await updateInventoryItem(editing,form):await addInventoryItem(form);setOpen(false);setEditing(null);await load()}
 async function remove(id){if(!confirm(L.confirmDelete))return;await deleteInventoryItem(id);setMenu(null);await load()}
 function exportCsv(){const head=['Type','Name','Color','HEX','Brand','Stock g','Ball g','Price/ball','Min stock','Value'];const data=rows.map(r=>[r.type,r.name,r.color_name,r.color_code,r.brand,r.stock_g,r.ball_g,r.price_per_ball,r.min_stock_g,r.value]);downloadCsv('tufting-inventory.csv',[head,...data])}
 return <div className="biz-page inventory-page"><section className="biz-frame inventory-frame"><span className="biz-number inventory-number">2</span>
  <header className="biz-page-head"><div className="biz-title-wrap"><span className="biz-title-icon inventory-icon"><Archive/></span><div><h1>{L.inventory}</h1><p>{L.sub}</p></div></div><div className="biz-head-actions"><button className="biz-soft-btn" onClick={exportCsv}><Download/>{L.export}</button><div className="biz-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={L.search}/></div><button className="biz-primary inventory-primary" onClick={startAdd}><Plus/>{L.add}</button></div></header>
  <div className="inventory-layout"><div className="biz-table-wrap"><table className="biz-table inventory-table"><thead><tr><th>{L.yarn}</th><th>{L.color}</th><th>{L.hex}</th><th>{L.stock}</th><th>{L.priceBall}</th><th>{L.stockAlert}</th><th></th></tr></thead><tbody>{filtered.map(r=>{const low=Number(r.stock_g)<=Number(r.min_stock_g);return <tr key={r.id}><td><div className="yarn-cell"><span className="yarn-ball" style={{background:r.color_code}}/><strong>{r.name}</strong></div></td><td><span className="color-chip" style={{background:r.color_code}}/>{r.color_name||'—'}</td><td>{r.color_code}</td><td>{fmt(r.stock_g)} g</td><td>{eur(r.price_per_ball)}</td><td>{low?<span className="stock-pill low"><AlertTriangle/>{L.low}</span>:<span className="stock-pill ok">OK</span>}</td><td className="menu-cell"><button className="dots" onClick={()=>setMenu(menu===r.id?null:r.id)}><MoreHorizontal/></button>{menu===r.id&&<div className="row-menu"><button onClick={()=>startEdit(r)}><Pencil/>{L.edit}</button><button className="danger" onClick={()=>remove(r.id)}><Trash2/>{L.delete}</button></div>}</td></tr>})}</tbody></table>{loading&&<div className="biz-empty">{L.loading}</div>}{!loading&&!filtered.length&&<div className="biz-empty">{L.empty}</div>}</div>
   <aside className="inventory-summary"><h3>{L.summary}</h3><Donut rows={rows} total={totalG}/><div className="inventory-legend">{rows.slice(0,7).map(r=><div key={r.id}><span><i style={{background:r.color_code}}/>{r.color_name||r.name}</span><b>{fmt(r.stock_g)} g</b></div>)}</div><div className="inventory-total"><span>{L.totalValue}</span><strong>{eur(totalValue)}</strong></div></aside>
  </div>
 </section>
 <BusinessModal open={open} onClose={()=>setOpen(false)} title={editing?L.editItem:L.add} subtitle={L.formSub} wide><form className="biz-form two-col" onSubmit={save}><label><span>{L.type}</span><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="Yarn">Yarn</option><option value="Backing">Backing</option><option value="Glue">Glue</option><option value="Felt">Felt</option><option value="Other">Other</option></select></label><label><span>{L.name}</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label><span>{L.color}</span><input value={form.color_name} onChange={e=>setForm({...form,color_name:e.target.value})}/></label><label><span>{L.hex}</span><div className="hex-row"><input type="color" value={form.color_code} onChange={e=>setForm({...form,color_code:e.target.value.toUpperCase()})}/><input value={form.color_code} onChange={e=>setForm({...form,color_code:e.target.value})}/></div></label><label><span>{L.brand}</span><input value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})}/></label><label><span>{L.stock}</span><div className="input-unit"><input inputMode="decimal" value={form.stock_g} onChange={e=>setForm({...form,stock_g:e.target.value})}/><b>g</b></div></label><label><span>{L.ballG}</span><div className="input-unit"><input inputMode="decimal" value={form.ball_g} onChange={e=>setForm({...form,ball_g:e.target.value})}/><b>g</b></div></label><label><span>{L.priceBall}</span><div className="input-unit"><b>€</b><input inputMode="decimal" value={form.price_per_ball} onChange={e=>setForm({...form,price_per_ball:e.target.value})}/></div></label><label><span>{L.minStock}</span><div className="input-unit"><input inputMode="decimal" value={form.min_stock_g} onChange={e=>setForm({...form,min_stock_g:e.target.value})}/><b>g</b></div></label><div className="biz-form-actions span-2"><button type="button" className="biz-soft-btn" onClick={()=>setOpen(false)}>{L.cancel}</button><button className="biz-primary inventory-primary">{L.save}</button></div></form></BusinessModal>
 </div>
}
function Donut({rows,total}){let pos=0;const seg=rows.slice(0,8).map(r=>{const pct=total?Number(r.stock_g)/total*100:0;const a=pos;pos+=pct;return `${r.color_code} ${a}% ${pos}%`});return <div className="donut" style={{background:seg.length?`conic-gradient(${seg.join(',')})`:'#eee'}}><div><small>Totali</small><strong>{fmt(total)} g</strong></div></div>}
function fmt(v){return new Intl.NumberFormat('de-DE',{maximumFractionDigits:0}).format(Number(v)||0)} function eur(v){return new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(v)||0)}
function downloadCsv(name,rows){const csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function labels(lang){const sq={inventory:'Inventari',sub:'Menaxho stokun e materialeve dhe leshit për projektet e tua.',export:'Eksporto',search:'Kërko material...',add:'Shto material',yarn:'Leshi',color:'Ngjyra',hex:'Kodi HEX',stock:'Stoku (g)',priceBall:'Çmimi/top',stockAlert:'Alarm stok',summary:'Përmbledhje stoku',totalValue:'Vlera totale e inventarit',low:'Stok i ulët',edit:'Redakto',delete:'Fshi',loading:'Duke ngarkuar...',empty:'Nuk ka materiale të regjistruara.',editItem:'Redakto materialin',formSub:'Stoku dhe vlera ruhen në Firestore.',type:'Lloji',name:'Emri',brand:'Marka',ballG:'Gramatura/top',minStock:'Minimumi i stokut',cancel:'Anulo',save:'Ruaj materialin',confirmDelete:'Ta fshij këtë material?'};const de={...sq,inventory:'Inventar',sub:'Bestand an Garn und Materialien verwalten.',export:'Exportieren',search:'Material suchen...',add:'Material hinzufügen',yarn:'Garn',color:'Farbe',stock:'Bestand (g)',priceBall:'Preis/Knäuel',stockAlert:'Bestandsalarm',summary:'Bestandsübersicht',totalValue:'Gesamtwert des Inventars',low:'Niedriger Bestand',edit:'Bearbeiten',delete:'Löschen',loading:'Wird geladen...',empty:'Keine Materialien gespeichert.',editItem:'Material bearbeiten',formSub:'Bestand und Wert werden in Firestore gespeichert.',type:'Typ',name:'Name',brand:'Marke',ballG:'Gramm/Knäuel',minStock:'Mindestbestand',cancel:'Abbrechen',save:'Material speichern',confirmDelete:'Dieses Material löschen?'};const en={...sq,inventory:'Inventory',sub:'Manage yarn and material stock for your projects.',export:'Export',search:'Search material...',add:'Add material',yarn:'Yarn',color:'Color',stock:'Stock (g)',priceBall:'Price/ball',stockAlert:'Stock alert',summary:'Stock summary',totalValue:'Total inventory value',low:'Low stock',edit:'Edit',delete:'Delete',loading:'Loading...',empty:'No materials saved.',editItem:'Edit material',formSub:'Stock and value are saved in Firestore.',type:'Type',name:'Name',brand:'Brand',ballG:'Grams/ball',minStock:'Minimum stock',cancel:'Cancel',save:'Save material',confirmDelete:'Delete this material?'};return lang==='de'?de:lang==='en'?en:sq}
